apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  finalizers:
    - lvmcluster.topolvm.io
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - default: true
        deviceSelector:
          forceWipeDevicesAndDestroyAllData: true
          paths:
            - /dev/vdb
        fstype: ext4
        name: ocp
        thinPoolConfig:
          chunkSizeCalculationPolicy: Static
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
